CREATE TABLE USER_SYSTEM(
	ID VARCHAR(21) PRIMARY KEY,
	FIRST_NAME VARCHAR(11),
	LAST_NAME VARCHAR(11),
	EMAIL VARCHAR(51),
	PHONE VARCHAR(12),
	BIRTH_DATE DATE,
	GENDER VARCHAR(7),
	ADDRESS VARCHAR(51),
	CREATED_AT TIMESTAMP WITH TIME ZONE,
	MODIFIED_AT TIMESTAMP WITH TIME ZONE
)

CREATE TABLE ACCOUNT(
	ID VARCHAR(21) PRIMARY KEY,
	USER_ID VARCHAR(21) REFERENCES USER_SYSTEM(ID),
	PASSWORD TEXT,
	STATUS BOOL,
	ROLE VARCHAR(11),
	MODIFIED_AT TIMESTAMP WITH TIME ZONE
)

CREATE TABLE PRODUCT(
	ID VARCHAR(21) PRI		MARY KEY,
	NAME VARCHAR(101),
	DESCRIPTION TEXT,
	PRICE FLOAT,
	STATUS VARCHAR(5),
	INFORMATION TEXT,
	CREATED_AT TIMESTAMP WITH TIME ZONE,
	MODIFIED_AT TIMESTAMP WITH TIME ZONE
)

SELECT * FROM ACCOUNT
SELECT * FROM USER_SYSTEM
SELECT * FROM PRODUCT

DELETE FROM ACCOUNT
DELETE FROM USER_SYSTEM

DROP TABLE ACCOUNT
DROP TABLE USER_SYSTEM