Register User
###
POST http://localhost:8080/user/api
Content-Type: application/json

{
    "firstName": "Nguyễn",
    "lastName": "Trí",
    "phone": "0938671192",
    "email": "nguyentri.alan@gmail.com",
    "gender": "male",
    "address": "23",
    "birthDate": "2001-04-04",
    "password": "123456",
    "role": "admin"
}


###
POST http://localhost:8080/user/api
Content-Type: application/json

{
    "firstName": "Vy",
    "lastName": "Hoa",
    "phone": "0938671215",
    "email": "hoa@gmail.com",
    "gender": "male",
    "address": "23",
    "birthDate": "2001-04-04",
    "password": "123456",
    "role": "client"
}

###
PUT http://localhost:8080/user/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuMnhqcWRxbmNqbjF5MjV6Z21mMiIsImlhdCI6MTY3NzczMTU0OX0.0UdiNU-qwZoWaO73isn8tfcDHkm7Z1GlI4oYGvgTOMs

{
    "firstName": "Nguyen",
    "lastName": "Tri",
    "phone": "2323",
    "gender": "male",
    "address": "23",
    "birthDate": "2001-04-04"
}


###
PUT http://localhost:8080/product/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuMnhqcWRxbmNqbjF5MjV6Z21mMiIsImlhdCI6MTY3NzczMTU0OX0.0UdiNU-qwZoWaO73isn8tfcDHkm7Z1GlI4oYGvgTOMs

{
    "firstName": "Nguyen",
    "lastName": "Tri",
    "phone": "2323",
    "gender": "male",
    "address": "23",
    "birthDate": "2001-04-04"
}
###
GET http://localhost:8080/user/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiNjZybjRpeDNleDdzamtzMnkweCIsImlhdCI6MTY3OTU0OTEyN30.Y3f-e_wxyxG3MaO2q3kvQ3uyyYIhUCeajce9UDQ1Tl4

###
POST http://localhost:8080/account/api
Content-Type: application/json

{
    "email": "hoa@gmail.com",
    "password": "123456"
}

###
POST http://localhost:8080/distributor/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiNjZybjRpeDNleDdzamtzMnkweCIsImlhdCI6MTY3OTU0OTUwMn0.XwUvQnWst619E8xH3MYn7DS7Qtpn2wzEhliFkSpGH_Y

{
    "phone": "0902323232",
    "name": "FShop"
}

###
POST http://localhost:8080/detail/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiNjZybjRpeDNleDdzamtzMnkweCIsImlhdCI6MTY3OTU0OTUwMn0.XwUvQnWst619E8xH3MYn7DS7Qtpn2wzEhliFkSpGH_Y

{
    "productId": "sv2boa4h87kaneczfsb2",
    "products": [
        {
            "color": 0,
            "specifications": "2GB RAM",
            "price": "2500000"
        },
        {
            "color": 0,
            "specifications": "4GB RAM",
            "price": "3000000"
        },
        {
            "color": 0,
            "specifications": "16GB RAM",
            "price": "3200000"
        }
    ],
    "quantities": [100, 103, 29],
    "discounts": [10, 10, 10]
}

###
PUT http://localhost:8080/account/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuMnhqcWRxbmNqbjF5MjV6Z21mMiIsImlhdCI6MTY3NzcyMTk1OH0.ladprmDdB_gU5wXFodbyu_X1ZkUR704zeJ6ZbepnmWY

{
    "oldPassword": "123456",
    "newPassword": "123455"
}

###
POST http://localhost:8080/product/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiNjZybjRpeDNleDdzamtzMnkweCIsImlhdCI6MTY3OTU1MDI3Mn0.22xdK4tglKU7a8V11ll2m8rOgu6LTmM2ECqznRyErOA

{
    "name": "Raspberry Pi 4 Model B",
    "description": "Raspberry Pi Foundation lại tiếp tục làm người dùng bất ngờ khi tung ra phiên bản Raspberry Pi 4 8GB hoàn toàn mới, không lâu sau khi dừng sản xuất phiên bản 1GB RAM",
    "information": "Test"
}

###
GET http://localhost:8080/product/6vj0x1jwq3fjzqd0z0ju
Content-Type: application/json

###
GET http://localhost:8080/review/product?id=6vj0x1jwq3fjzqd0z0ju
Content-Type: application/json

###
POST http://localhost:8080/category/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuMnhqcWRxbmNqbjF5MjV6Z21mMiIsImlhdCI6MTY3ODc4MzA4OX0.F8psmquIrjR2KgZn71lesXlBnRWxRIKwJFprYMoMiCc

{
    "name": "Raspberry Pi"
}

###
PUT http://localhost:8080/warehouse/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuMnhqcWRxbmNqbjF5MjV6Z21mMiIsImlhdCI6MTY3ODc4MzA4OX0.F8psmquIrjR2KgZn71lesXlBnRWxRIKwJFprYMoMiCc

{
    "productId": "ezxyaxwe6zc1otnz9aq0",
    "quantity": 100,
    "type": "plus"
}

###
POST http://localhost:8080/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuemZ6dTc2YTFlNXk1Z20xMm8zaCIsImlhdCI6MTY3OTU4Mjg0NX0.IGsZ0mhkuepqDuHSla3k2j9js7hH0MGuqv0PA9EO8f0

{
    "productId": "6hmez9zidottukc2tdwo",
    "quantity": 5
}

###
POST http://localhost:8080/category/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuemZ6dTc2YTFlNXk1Z20xMm8zaCIsImlhdCI6MTY3OTU4MTMyM30._Xx8JNrL9osHWQGW8JVs_4OcWFYXzPF8kxxEAOUoHdg

{
    "name": ""
}

###
GET http://localhost:8080/category/api?page=1&num=5
Content-Type: application/json

###
PUT http://localhost:8080/cart/status/0yvmgcp058ed6lslpw5p
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuemZ6dTc2YTFlNXk1Z20xMm8zaCIsImlhdCI6MTY3OTYzMDAzMH0.A9UgqJ-a25UxC43jCx4mdA2vN0j4zaj1OF23WHqAESU


###
PUT http://localhost:8080/cart/all?status=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuemZ6dTc2YTFlNXk1Z20xMm8zaCIsImlhdCI6MTY3OTYzMDAzMH0.A9UgqJ-a25UxC43jCx4mdA2vN0j4zaj1OF23WHqAESU
###
POST http://localhost:8080/order/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuemZ6dTc2YTFlNXk1Z20xMm8zaCIsImlhdCI6MTY3OTYzMDAzMH0.A9UgqJ-a25UxC43jCx4mdA2vN0j4zaj1OF23WHqAESU

{
    "paymentType": "CASH",
    "status": "COMPREHENSIVE"
}
###
GET http://localhost:8080/bill/c82yknvofavfqw02o5r2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuemZ6dTc2YTFlNXk1Z20xMm8zaCIsImlhdCI6MTY3OTYzMDAzMH0.A9UgqJ-a25UxC43jCx4mdA2vN0j4zaj1OF23WHqAESU


###
GET http://localhost:8080/bill/teu40d2rkd968dgo0yql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuemZ6dTc2YTFlNXk1Z20xMm8zaCIsImlhdCI6MTY3OTYzMDAzMH0.A9UgqJ-a25UxC43jCx4mdA2vN0j4zaj1OF23WHqAESU

###
GET http://localhost:8080/order/review?reviewed=0&status=COMPREHENSIVE
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuemZ6dTc2YTFlNXk1Z20xMm8zaCIsImlhdCI6MTY3OTYzMDAzMH0.A9UgqJ-a25UxC43jCx4mdA2vN0j4zaj1OF23WHqAESU

###
GET http://localhost:8080/cart/api?page=1&num=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuMnhqcWRxbmNqbjF5MjV6Z21mMiIsImlhdCI6MTY3ODg1MjQyMH0.5fR1uOof1P0mMUDBDreUPlNwPyPw1oU2PyDM0cka4Uw


###
POST http://localhost:8080/review/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuemZ6dTc2YTFlNXk1Z20xMm8zaCIsImlhdCI6MTY3OTYzMDAzMH0.A9UgqJ-a25UxC43jCx4mdA2vN0j4zaj1OF23WHqAESU

{
    "orderId": 5,
    "content": "test api",
    "stars": 5
}


###
POST http://localhost:8080/comment/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiNjZybjRpeDNleDdzamtzMnkweCIsImlhdCI6MTY3OTcyNjA4MX0.j7oFlL5mjri_NFXjtx_I6VLet34eoc7uS7RDnHcgc1k

{
    "productId": "sv2boa4h87kaneczfsb2",
    "content": "reply 2",
    "reply": "nkn2ul4a3vktnlscij5p"
}

###
GET http://localhost:8080/comment/api?id=sv2boa4h87kaneczfsb2
Content-Type: application/json

###
GET http://localhost:8080/account/mail
Content-Type: application/json


###
GET http://localhost:8080/user/admin
Content-Type: application/json

###
GET http://localhost:8080/product/show
Content-Type: application/json

###
GET http://localhost:8080/detail/show?page=1&num=3
Content-Type: application/json


###
GET http://localhost:8080/warehouse/show?page=1&num=3
Content-Type: application/json

###
GET http://localhost:8080/warehouse/history/6hmez9zidottukc2tdwo?descending=0
Content-Type: application/json

###
GET http://localhost:8080/bill/show?page=1&num=2
Content-Type: application/json

###
POST http://localhost:8080/detail/save
Content-Type: application/json

{
    "productId": "a021dqh6txsf9zywlzhe",
    "colors": [4,5,6],
    "specifications": "SSD 1TB RAM 64GB",
    "price": "8000000",
    "status": true,
    "discount": "5",
    "quantity": "10",
    "images": ["test4", "test27"]
}
