@host=http://localhost:8080

POST {{host}}/user/api
Content-Type: application/json

{
    "firstName": "Hoa",
    "lastName": "Vy",
    "phone": "001293921",
    "email": "hoavy@gmail.com",
    "gender": "Male",
    "address": "Thu Duc, Ho Chi Minh, Vietnam",
    "birthDate": "2001-05-07",
    "password": "123456",
    "role": "admin"
}